title: devKwanghoKim 블로그 
description: 개발 기록 블로그
theme: just-the-docs
url: "https://devKwanghoKim.github.io"
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      layout: default              
