title: devKwanghoKim 
description: 개발 기록 블로그
theme: just-the-docs
url: "https://devKwanghoKim.github.io"
baseurl: ""

aux_links:
  GitHub: https://github.com/devKwanghoKim

defaults:
  - scope:
      path: ""
    values:
      layout: default              
